pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'io.freefair.android-lombok') {
                useModule("com.github.plumguardian:android-gradle-plugins:${requested.version}")
            }
        }
    }
}

include ':FtcRobotController'
include ':TeamCode'
